services:
  ros_noetic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros_noetic_sim
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../ros_ws:/ros_ws
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "110"
    stdin_open: true
    tty: true
    privileged: true
